version: '3.9'
services:
  php:
    restart: always
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/var/www/html/
    ports:
      - "80:80"
  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    volumes:
      - ./mssql/data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rdnimda
      - MSSQL_COLLATION=Thai_CI_AS
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
